# Generated by Django 3.1.7 on 2021-03-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_auto_20210330_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
