# Generated by Django 3.1.7 on 2021-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_auto_20210330_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
