# Generated by Django 3.1.7 on 2021-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0007_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.ManyToManyField(to='moviesapp.Status'),
        ),
    ]
